### ISSUE TITLE
[質問] 拡散反射について

### ISSUE THREAD

**Issue by ryo-manba** [ryo-manba/miniRT#1]
1. 衝突した点から、光源までのベクトルを求めるにはどうするか。
2. この場合の光源は、Ambient lightningを指すのか、それとも Light の方を指すか。
3. 衝突点から光源までのベクトルの途中で、他のオブジェクトと衝突した場合の処理はどうするか。

以上3点です。回答お願いします。

**Comment by corvvs** [comment]
> 衝突した点から、光源までのベクトルを求めるにはどうするか。

2点間のベクトルを求めれば良いと思います。
つまり、`光源の位置ベクトル - 衝突点の位置ベクトル`です。

> この場合の光源は、Ambient lightningを指すのか、それとも Light の方を指すか。

これについては確固たる情報源がないので調べてみます。
少なくともLightは「光源」です。
~~また、何にも当たらなかった場合は「Ambient Lightingに当たった」とみなすことになると思います。~~
「何にも当たらない」ことはありないので、↑の記述は誤りです。すみません。

> 衝突点から光源までのベクトルの途中で、他のオブジェクトと衝突した場合の処理はどうするか。

その光源についての処理を打ち切れば良いと思います。

**Comment by ryo-manba** [comment]
了解しました。ありがとうございます。
