### ISSUE TITLE
[協議] ライト`L`はただ1つか？

### ISSUE THREAD

**Issue by corvvs** [ryo-manba/miniRT#10]
今までライト`L`は複数あることを想定していましたが、課題PDFをよく読むとライトも1つっぽいです。
今ライトは複数あることを前提にしていますが、複数対応しているとMandatoryのレビューで落とされる可能性がなくもないと思います。
これについて対応を協議したいです。

**Comment by ryo-manba** [comment]
> Elements which are defined by a capital letter can only be declared once in the scene.

この部分ってことですよね。

Mandatoryに関しては大文字`L`が2つ以上ある場合に、rtファイルの読み込み部分でエラーを出す必要があると思いますが、
Bonusの場合、multi-spot lights対応があるので、lightsの処理は複数対応でいいんじゃないでしょうか？

`while(lights[i] != NULL)`でライトの処理をするみたいなイメージです。
