### ISSUE TITLE
[質問] 幅を2.0に固定する

### ISSUE THREAD

**Issue by corvvs** [ryo-manba/miniRT#11]
現状、ビューポートの高さは2.0で固定されており、幅は縦横比に応じて変わるようになっています。
ですが、カメラのパラメータ`FOV`は「水平方向」の視野角になっています。
そのため、ビューポートの幅の方を固定した方が良いような気がしています。
検討をお願いします。

**Comment by ryo-manba** [comment]
視野角とビューポートの関係性がまだ理解できていないので、ひとまず固定してしまって大丈夫です！
調べてみて、何かあればまたお伝えします！

**Comment by ryo-manba** [comment]
視野角とビューポートの幅を元に三角比を利用することで、視点からビューポートまでの焦点距離が求まる。
そのため、幅を固定する。
という認識で合ってますでしょうか？

**Comment by corvvs** [comment]
> 視野角とビューポートの幅を元に三角比を利用することで、視点からビューポートまでの焦点距離が求まる。

これはYesです。

>  そのため、幅を固定する。

今の状態でも焦点距離の計算は可能ですが、幅を定数にしておくと話がわかりやすくなります。
