### ISSUE TITLE
[質問] チェッカーボードについて

### ISSUE THREAD

**Issue by corvvs** [ryo-manba/miniRT#22]
### パラメータ`theta, phi`とは何か？

これは、それぞれ方位角・仰角と呼ばれる角度です。
半径が分かっている場合、方位角・仰角が分かれば、球面上の位置を特定することができます。

- `theta = atan2(x, z);` は、X軸を横軸、Z軸を縦軸に取った時の、横軸から測った角度を表します。
  - `atan2`は-πから+πまでの値を取るので、`theta`もそうなります。
- `phi = acos(y);` は、Y軸を縦軸に取った時の、縦軸から測った角度を表します。
  - `acos`は0からπまでの値を取るので、`phi`もそうなります。

<img src="https://user-images.githubusercontent.com/10496148/145710925-1ea7e8fc-d286-4f88-856f-62d9a67b1521.JPG" width=300>

※thetaを仰角、phiを方位角とするのが一般的です。

### パラメータ`u,v`とは何か？

`theta, phi`はラジアン単位の角度なので、-πから+πまでの値を取ります。
これを、-1から+1までの値を取るように補正したものが`u, v`と考えられます。
- `u = 1 - (theta / (2 * M_PI) + 0.5)`
  - `theta`は-πから+πまでの値を取るので、`u`は1から0までの値を取ります。
- `v = 1 - (phi / M_PI)`
  - `phi`は0から+πまでの値を取るので、`v`は0から1までの値を取ります。
  - `y = +1`の時`phi = 0`,` y = 0`の時` phi = π/2`, `y = -1`の時`phi = π`となります。
  - `v`はそれぞれ`1, 1/2, 0`となります。

`u, v`の「意味」を考えるために、原点`(0, 0, 0)`を中心とする半径1の球面を考えます。
この球の「南極」`(0, -1, 0)`から「北極」`(0, +1, 0)`に向かって、球面上に線を描きます。
これはいわゆる「経線」となります。

この時、パラメータ`v`は「経線上の長さ」に相当します。南極から出発した直後では`v = 0`, 
「赤道」上では`v = 1/2`, 北極についた時点で`v = 1`となります。

また、球面上にyを一定とする線を描くと、これは「緯線」に相当します。
パラメータ`u`は「緯線上の長さ」に相当します。

### `double sines = sin(m_freq * u) * sin(m_freq * v);`の意味

サイン関数`sin(x)`は、`0 <= x <= π`ならば0以上、`π <= x <= 2π`なら0以下の値を取ります。
それ以外の範囲では、たとえば`-π <= x <= 0`ならば0以下の値を取る、という風に、
0以下の値、0以上の値、0以下の値・・・・という風にπごとに繰り返します。

そして、掛け算により
- (0以下の値) x (0以下の値) = (0**以上**の値)
- (0以下の値) x (0以上の値) = (0**以下**の値)
- (0以上の値) x (0以下の値) = (0**以下**の値)
- (0以上の値) x (0以上の値) = (0**以上**の値)

という風に変化します。
表にすると、

||0以上の値|0以下の値|0以上の値|0以下の値|
|-|-|-|-|-|
|0以上の値|0**以上**の値|0**以下**の値|0**以上**の値|0**以下**の値|
|0以下の値|0**以下**の値|0**以上**の値|0**以下**の値|0**以上**の値|
|0以上の値|0**以上**の値|0**以下**の値|0**以上**の値|0**以下**の値|
|0以下の値|0**以下**の値|0**以上**の値|0**以下**の値|0**以上**の値|

という風に、0以上と0以下がチェッカーボード状に変化します。

サイン関数を、定数`a`を使って`sin(ax)`に書き直すと、値の変化は
`0 <= x <= π/a`ならば0以上、`π/a <= x <= 2π/a`ならば0以下、となります。
さらに`a = πb`とすると、
`0 <= x <= 1/b`ならば0以上、`1/b <= x <= 2/b`ならば0以下、となります。
よって、例えばa = 4πとすると、
`0 <= x <= 1/4`ならば0以上、`1/4 <= x <= 1/2`ならば0以下、となります。
つまり、一周当たり4回変化することになります。

### 実は

```c
double sines = sin(m_freq * u * M_PI) * sin(m_freq * v * M_PI);
if (sines > 0)
{ ... }
else
{ ... }
```

は、

```c
int sines = (int)(floor(m_freq * u) + floor(m_freq * v));
if (sines % 2 == 0)
{ ... }
else
{ ... }
```
とほぼ同じになります。

## 質問1

https://github.com/ryo-manba/miniRT/blob/69559f9f1740bd9ad5f92c1124a68c2328bb74ac/rt_object_sphere.c#L43

`M_PI`で割っているのはなぜでしょう？

## 質問2

https://github.com/ryo-manba/miniRT/blob/69559f9f1740bd9ad5f92c1124a68c2328bb74ac/main.c#L72

`sinf`(float返すバージョンのsin)を使ってるのはなぜでしょう？
(`sin`で良い気がします)

## 質問3

https://github.com/ryo-manba/miniRT/blob/69559f9f1740bd9ad5f92c1124a68c2328bb74ac/main.c#L72

最後の` * sin(m_freq * -10)`はなぜ必要なのでしょうか？
(定数なので別にいらないような)

**Comment by ryo-manba** [comment]
解説ありがとうございます！

以下質問の回答です。

> M_PIで割っているのはなぜでしょう？

極座標を求めるのに必要らしいです。(正確には分かってないです)

> sinf(float返すバージョンのsin)を使ってるのはなぜでしょう？

sin で良かったです。

> 最後の * sin(m_freq * -10)はなぜ必要なのでしょうか？

色々試してました。適当な値を入れてただけなので、なくて良いみたいですね。

**Comment by corvvs** [comment]
ありがとうございます。

>> M_PIで割っているのはなぜでしょう？

> 極座標を求めるのに必要らしいです。(正確には分かってないです)

これに関しては多分不要だと思います

**Comment by ryo-manba** [comment]
了解しました。

`double phi = acos(rec->normal.y);`
にするとチェッカーボードの柄が縦長から横長に変わりました。
仕組みはよくわかってないのですが、問題なさそうなので上記に書き換えておきます。

**Comment by corvvs** [comment]
>  にするとチェッカーボードの柄が縦長から横長に変わりました。

元の`double phi = acos(rec->normal.y / M_PI);`の物理的・数学的な意味づけは不明ですが、
効果としては、パラメータ`phi`の取りうる範囲が0〜π**ではなく**0.397π〜0.603πとなり、範囲が約1/5ほどに狭くなります。
これは、球の模様が上下方向に5倍引き伸ばされることを意味します。

また、`acos(x)`関数は`x=0`付近ではほぼ直線になるので、縦方向の模様の変化の仕方も少し変わります
(上下端に近づくほどより長くなる?)。
