### ISSUE TITLE
[bugfix] 鏡面反射にバグがありそう -> なかった。むしろ円錐にバグがあった。

### ISSUE THREAD

**Issue by corvvs** [ryo-manba/miniRT#27]
## 現象

```txt
A  0.3      100,100,200
L  0,2000,0  0.8         255,0,0
C  0,0,-2  0,0,+1 90
co 0,0,10   0,0,-1   90 200,200,200
```

**シャドウの判定をしない状態で**、上のRTファイルから、次の画像が得られる:

![image](https://user-images.githubusercontent.com/10496148/147244864-0ba77013-ec3f-4a50-9b7c-ffd6808b1bd8.png)

状況を説明しておくと、

- ライトは原点から遥か上空にいる。色は赤い。
- カメラは原点のZ軸少し後方から、Z軸正方向を見ている
- 円錐はカメラの正面にいて、カメラをすっぽり覆っている。色は明るい灰色。
  - カメラの視界はすべて円錐の内側にあり、一方ライトは円錐の外側にいる。

この状態では、円錐内にはライトの光は侵入しないはずだが、画像では赤い色がついている。\
これは明らかに正しくない。

鏡面反射をカットすると赤色は消えたので、鏡面反射にバグがあると考えられる。

**Comment by corvvs** [comment]
円柱で同様の状態を作ってみたが、赤色がつかないので、円錐のバグかもしれない。
うーん。

**Comment by corvvs** [comment]
> シャドウの判定をしない状態で、上のRTファイルから、次の画像が得られる:

シャドウを判定しないなら、反射をするのは当然・・・

**Comment by corvvs** [comment]
あと円錐の処理にバグがありました・・・(法線ベクトルが逆になってた)
これが主要な原因だった模様。

**Comment by corvvs** [comment]
シャドウ判定がfalseだった場合は黒じゃなくてアンビエントの色はつくんじゃないの？

**Comment by ryo-manba** [comment]
ミスです！アンビエントの色はつくと思います！
