### ISSUE TITLE
submit前チェックリスト

### ISSUE THREAD

**Issue by ryo-manba** [ryo-manba/miniRT#37]
- [x] Subject最終確認
- [x] **(YK担当)**norminette通す
- [x] **(RM担当)**rtfile読み込みのテスター作成
- [x] **(RM担当)**それぞれの図形のrtfile追加
- [x] **(YK担当)**Leakチェック
- [x] (YK担当)`nm -u` で使用可能関数確認
- [x] (YK担当)日本語のコメント確認
- [x] (YK担当)ESCキーで終了
- [x] 解像度1080p
- [x] ボーナス分割？
- [x] leaks/valgrindを使ったリークチェック

**Comment by corvvs** [comment]
## 要対応項目

- [x] (RM) オブジェクト内に視点があるRTファイルをもうちょっと作る(3つくらい？)
- [x] (YK) `.rt`で終わってないファイルを与えた場合、中身がちゃんとしたRTファイルならレンダリングされる
