### ISSUE TITLE
[質問] 色ベクトル*など*について

### ISSUE THREAD

**Issue by corvvs** [ryo-manba/miniRT#4]
色ベクトル`t_rgb`は各要素が`int`になってますが、できれば`double`に変えたいです。不都合ありますでしょうか？
また、FOVも`int`になっていますが、これも`double`にしたいです。
(というかオブジェクトの数値はすべて`double`にしたい。)

**Comment by ryo-manba** [comment]
オブジェクトの数値をdoubleに統一する件了解しました。
`t_rgb`を`double`にする場合、`0xTTRRGGBB`の形式に変換する時に`int`にキャストするだけって認識で合ってますか？
```
int color = (t<<24|(int)r<<16 |(int)g<<8|(int)b); // 合ってます？
```

**Comment by corvvs** [comment]
ありがとうございます。

> intにキャストするだけ

です！

**Comment by ryo-manba** [comment]
了解しました！
